config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  root 'users#home'
  get '/expenselist' => 'users#expenselist'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post 'expenses/create', to: "expenses#create"
  post 'guests/create', to: 'guests#create'
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :events do
    resources :expenses, only: [:new, :edit, :destroy, :create, :update]
    resources :guests, only: [:new, :destroy, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :expenses
  has_many :guests

  validates :name, presence: true
  validates :budget, presence: true


  def budget_difference
    expenses_array = self.expenses.collect { |event| event.total }
    expenses_total = expenses_array.inject(0){|sum,x| sum + x }
    return self.budget - expenses_total
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :event
  
  default_scope { order(cost: :desc) }

  def total
    return self.cost * self.quantity if self.cost && self.quantity
  end

  def bought
    self.purchased = true
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :event
  
  default_scope { order(name: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :expenses, through: :events
  has_many :guests, through: :events

  has_secure_password
  validates :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    @user = (User.find_by(id: session[:user_id]) || User.new)
  end

  def logged_in?
    current_user.id != nil
  end

  def require_logged_in
    return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :destroy, :update]
  before_action :set_user, only: [:show, :edit, :destroy, :update, :index]

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    @event.user_id = session[:user_id]
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def show
    if @user == @event.user_id
      @user = User.find(@event.user_id)
      @expense = Expense.new
      @expenses = @event.expenses.all
      @guest = Guest.new
      @guests = @event.guests.all
      @difference = @event.budget_difference
      respond_to do |format|
          format.json {render json: @event, status: 200}
        format.html {render :show}
      end
    else
      redirect_to root_path
    end
  end

  def index
    current_user = User.find(@user)
    @events = current_user.events
    respond_to do |format|
      format.json{render json: @events, status: 200}
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

  def set_user
    @user = session[:user_id]
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :budget, :users_id)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  before_action :set_expense, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:edit, :update, :destroy, :create]

  def edit
  end

  def update
    if params[:user_id] = session[:user_id]
      if @expense.update(expense_params)
        redirect_to event_path(@expense.event.id)
      else
        render :edit
      end
    else
      redirect_to root_path
    end
  end

  def create
    if params[:user_id] = session[:user_id]
      @event = Event.find(params[:expense][:event_id])
      @expense = @event.expenses.build(expense_params)
      @expense.save
      render json: @expense
    else
      redirect_to root_path
    end
  end

  def destroy
    if params[:user_id] = session[:user_id]
      @event = @expense.event_id
      @expense.destroy
      redirect_to event_path(@event)
    else
      redirect_to root_path
    end
  end

  private

  def set_user
    @user = session[:user_id]
  end

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:name, :cost, :quantity, :event_id, :purchased)
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_user, only: [:destroy, :create]
  before_action :set_guest, only: [:destroy]

  def create
    if params[:user_id] = session[:user_id]
      @event = Event.find(params[:guest][:event_id])
      @guest = @event.guests.build(guest_params)
      @guest.save
      render json: @guest
    else
      redirect_to root_path
    end
  end

  def destroy
    if params[:user_id] = session[:user_id]
      @event = @guest.event_id
      @guest.destroy
      redirect_to event_path(@event)
    else
      redirect_to root_path
    end
  end

  private

  def set_user
    @user = session[:user_id]
  end

  def set_guest
    @guest = Guest.find(params[:id])
  end

  def guest_params
    params.require(:guest).permit(:name, :event_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if request.env["omniauth.auth"]
      oauth_username = request.env["omniauth.auth"]["info"]["nickname"]
      @user = User.find_or_create_by(username: oauth_username) do |u|
        u.password = SecureRandom.hex
      end
      session[:user_id] = @user.id
      redirect_to root_path
    else
    flash[:password] = "Please enter a password" if params[:user][:password] == ""
    flash[:username] = "Please enter a username" if params[:user][:username] == ""
      @user = User.find_by(username: params[:user][:username])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash[:incorrect] = "Incorrect Password" if params[:user][:password] != ""
        redirect_to root_path
      end
    end
  end

  def destroy
    session.delete :user_id
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_logged_in, only: [:home]

  def new
    if logged_in?
      redirect_to users_home_url
    else
      @user = User.new
    end
  end

  def create
    @user = User.create(user_params)
    @errors = @user.errors.full_messages
    if @user.save
      session[:user_id] = @user.id
      return redirect_to root_path
    else
      render :new, flash: {alert: @user.errors.full_messages}
    end
  end

  def show
    @user = User.find(session[:user_id])
    render json: @user
  end

  def home
    @user = User.find(session[:user_id])
    @events = @user.events.all
  end

  def expenselist
    @user = User.find(session[:user_id])
    @expenses = @user.expenses

    render json: @expenses, status: 200

  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<div class="col-md-4 mb-3">
  <%= form_for @event, url: event_path, method: :PATCH do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :budget %>
    <%= f.number_field :budget, step: :any, class: "form-control" %><br>

    <%= f.submit "Update Event", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Create New Event</h1>
<div class="col-md-4 mb-3">
  <%= form_for @event, url: events_path do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :budget %>
    <%= f.number_field :budget, step: :any, class: "form-control" %>
<br>
    <%= f.submit "Create Event", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/events/show.html.erb
<br>
<div align="center">
  <h2>Event Info</h2>

  <p>Name - <%= @event.name %></p>
  <p>Budget - <%= number_to_currency(@event.budget) %></p>
  <p><%=link_to "Edit", edit_event_path(@event)%></p>
  <p>See all events created by <%= @event.user.username %></p>
  <div id="eventShow">
    <a href="/events.json" id="userEvents" type="submit"> Show </a>
    <table></table>
  </div>
  <br>
</div>


<h2>Expenses</h2><br>
  <table align="center" class="table table-striped" id="expense_table">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Cost</th>
        <th>Quantity</th>
        <th>Total</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  <% @expenses.each do |expense| %>
    <tr>
      <td></td>
      <td><%= expense.name %></td>
      <td><%= number_to_currency(expense.cost) %></td>
      <td><%= expense.quantity %></td>
      <td><%= number_to_currency(expense.total) %></td>
      <td><%= link_to "Edit", edit_event_expense_path(expense.event_id, expense.id) %></td>
      <td><%= link_to "Delete", event_expense_path(expense.event_id, expense.id), method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <h4>Budget Remaining: <%= number_to_currency(@difference) %></h4>
  <br>

<h4>Add an Expense</h4><br>
<div class="col-md-4 mb-3">
  <%= form_for @expense, url: url_for(controller: 'expenses', action: 'create') do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %><br>
    <%= f.label :cost %>
    <%= f.number_field :cost, step: :any, class: "form-control" %><br>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, value: 1, class: "form-control" %><br>
    <%= f.hidden_field :event_id, value: params[:id] %>
    <%= f.submit "Add Expense", data: {disable_with: false}, class: "btn btn-primary" %>
  <% end %>
</div>
  <br>



<h2>Guest List</h2>
<ol id="guest_list">
  <% @guests.each do |guest| %>
    <li><%= guest.name %> <%= link_to "Remove", event_guest_path(guest.event_id, guest.id), method: :delete %></li>
  <% end %>
</ol>

<h4>Add a Guest</h4>
<div class="col-md-4 mb-3">
  <%= form_for @guest, url: url_for(controller: 'guests', action: 'create') do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %><br>
    <%= f.hidden_field :event_id, value: params[:id] %>
    <%= f.submit "Add Guest to List", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/expenses/edit.html.erb
<h2>Edit Expense</h2>
<div class="col-md-4 mb-3">
  <%= form_for @expense, url: event_expense_path(params[:event_id], params[:id]), method: :patch do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %><br>
    <%= f.label :cost %>
    <%= f.number_field :cost, step: :any, class: "form-control" %><br>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, class: "form-control" %><br>
    <%= f.label :purchased? %>
    <%= f.check_box :purchased %><br>
    <%= f.submit "Update Expense", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style media="screen">

      tr:nth-child(1) {
        counter-reset: rowNumber;
      }
      table.table  tr {
        counter-increment: rowNumber;
      }
      table.table tr td:first-child::before {
        content: counter(rowNumber);
        min-width: 1em;
        margin-right: 0.5em;
      }
    </style>
  </head>

  <% if session[:user_id] %>
    <header>
      <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <%= link_to "Budget App", root_path, class: "navbar-brand" %>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Home", root_path, class: "nav-item nav-link active" %>

            <%= link_to "Logout", logout_path, method: :destroy, class: "nav-item nav-link" %>
          </div>
        </div>
      </nav>
    </header>
  <% end %>

  <body>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/expenselist.html.erb
<h2>List of Expenses to Buy</h2>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Cost</th>
    </tr>
  </thead>
  <% @expenses.each do |expense| %>
    <% if expense.purchased == true %>
      <tr>
        <td></td>
        <td><strike><%= link_to expense.name, edit_event_expense_path(expense.event_id, expense.id) %></strike></td>
        <td><strike><%= expense.quantity %></strike></td>
        <td><strike><%= number_to_currency(expense.cost) %></strike></td>
      </tr>
    <% else %>
      <tr>
        <td></td>
        <td><%= link_to expense.name, edit_event_expense_path(expense.event_id, expense.id) %></td>
        <td><%= expense.quantity %></td>
        <td><%= number_to_currency(expense.cost) %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/users/home.html.erb
<h1>Hi, <%= @user.username %>! </h1>
<br>
<% if @events == [] %>
    <h3>You have no events, click <%= link_to "here", new_event_url %> to add one</h3>
<% else %>
    <h3>Your Events</h3>
    <%= link_to "New Event", new_event_url %>
    <br><br>
    <table class="table table-striped" id="event_table">
      <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>Event Name</th>
          <th>Event Budget</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
    <% @events.each do |event| %>
      <tr>
        <td></td>
        <td><%= link_to event.name, event_path(event)%></td>
        <td><%= number_to_currency(event.budget) %></td>
        <td><%= link_to "Delete", event_path(event), :method => :delete %></td>
        <td><a class="eventBrief" href="/events/<%=event.id%>.json">Brief Info</a>
          <div id="briefedEvent<%=event.id%>">

          </div>
          <div id="briefedGuest<%=event.id%>">

          </div>
      </tr>
      <% end %>
    <% end %>
  </table>


<div id="showShoppingList">
  <h3> Shopping List </h3>
  <a href="/expenselist.json" id="shoppingList" type="submit">Show List</a>
  <table></table>
</div>

app/views/users/new.html.erb
<h1>Sign Up below!</h1>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:message] %>
  </div>
  <% end %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
      <% @user.errors.full_messages.each do |message| %>
      <% if  message != "Password digest can't be blank"%>
      <div class="alert alert-danger">
        <%= message %>
      </div>

      <%end%>
      <% end %>
  </div>
<% end %>
<div class="col-md-4 mb-3">
  <%= form_for @user, controller: 'users', action: 'create' do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %><br>

    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %><br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %><br>

    <%= f.submit %>
  <% end %>
</div>

app/views/welcome/home.html.erb
<h1>Hi, <%= @user.username %> </h1>
<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>
<br><br>
<% if @events == [] %>
    <h3>You have no events, click <%= link_to "here", new_event_url %> to add one</h3>
<% else %>
    <table>
      <tr>
        <td>Event Name</td>
        <td>Event Budget</td>
      </tr>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event_path(event)%></td>
        <td><%= event.budget %></td>
        <td><%= link_to "Delete", event_path(event), :method => :delete %></td>
        <td></td>
      </tr>
      <% end %>
    <% end %>
    </table>